### ISSUE TITLE
Error in init.d when template resolves <%= @should_manage_compaction %> as empty string.

### ISSUE THREAD

**Issue by fortman** [TWCable/puppet-adobe_em6#18]
In file
https://github.com/TWCable/puppet-adobe_em6/blob/11026da063bf8696062eca2c814e02cdd3912649/templates/aem_type.erb

If line 26
    MANAGE_COMPACTION="<%= @should_manage_compaction %>"
Evaluates to empty string
    MANAGE_COMPACTION=""

It will cause line 32 if statement to fail.  To get around this, the variable should be quoted to ensure it resolves to an empty string.
From
    if [ ${MANAGE_COMPACTION} == "true" ]; then
To
    if [ "${MANAGE_COMPACTION}" == "true" ]; then

**Comment by fortman** [comment]
Also on line 26, it should be
<%= scope['::adobe_em6::instance::should_manage_compaction'] %>

Newer versions of puppet have issues referencing variables from other classes.  Need to use scope reference

**Comment by fortman** [comment]
#19 Pull request merged into master.  Still need to create a release at this point.

**Comment by cculb** [comment]
Resolved by #19

**Comment by fortman** [comment]
+1
